title: Jito Tip Router Documentation
longtitle: Jito Tip Router Documentation
description: Jito Tip Router Documentation
url: "https://docs.tip-router.jito.network"

remote_theme: sighingnow/jekyll-gitbook

markdown: kramdown
syntax_highlighter_style: colorful

toc:
  enabled: true
  h_min: 1
  h_max: 3

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - assets

collections:
  about:
    output: true
    permalink: /:collection/:title/
    sort_by: weight
  onchain:
    output: true
    permalink: /:collection/:title/
    sort_by: weight
  operator:
    output: true
    permalink: /:collection/:title/
    sort_by: weight
  cranker:
    output: true
    permalink: /:collection/:title/
    sort_by: weight

ordered_collections:
  - about
  - onchain
  - operator
  - cranker
